name: Bug Report
description: Issue with the notebook or script
title: "[Bug]: "
labels: ["bug"]
assignees:
  - kamil-kaczmarek
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting the problem!
        
        Answer the questions below to help us understand the issue.
  - type: input
    id: notebook
    attributes:
      label: Notebook or script with bug
      placeholder: URL or notebook/script name
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Please describe the problem and paste logs
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: Specify Ray, Python and OS versions
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Issue Severity
      multiple: false
      options:
          - "Low: Minor problem."
          - "Medium: It is a significant difficulty but I can work around it."
          - "High: It blocks me from completing my task."
    validations:
        required: true
